//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sushi_Trif.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sushi
    {
        public int Id { get; set; }
        public string Image { get; set; }
        public string Name { get; set; }
        public string Compound { get; set; }
        public int Price { get; set; }
    }
}
